version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/fittrak-db:/var/lib/postgresql/data

  api:
    build:
      dockerfile: docker/Dockerfile.webapp.dev
      context: .
    command: ["sh", "scripts/start-dev.sh"]
    ports:
      - "8000:8000"
    volumes:
      - "./fittrak:/usr/src/app/fittrak"
      - "./ipython-data:/root/.ipython/profile_default"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_HASHIDS_SALT=${DJANGO_HASHIDS_SALT}
      - DJANGO_DEBUG=False
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENV=${SENTRY_ENV}
      - SENTRY_RELEASE=${SENTRY_RELEASE}
    depends_on:
      - db

  app:
    build:
      dockerfile: docker/Dockerfile.frontend
      context: .
    ports:
      - "8080:8080"
    volumes:
      - "./fittrak-client/src:/usr/src/app/src"
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:8000/graphql
    depends_on:
      - api

volumes:
  fittrak:
  fittrak-client:
  ipython-data:
